name: access-db

on: workflow_dispatch

jobs:
  build:
    runs-on: macOS-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.1.1' # the R version to install

      - name: install r packages # blastula
        run: Rscript -e "install.packages('RPostgres') install.packages('RPostgreSQL')" 

      - name: execute r script # email-from-r.R
        env: 
          DBNAME: ${{ secrets.DBNAME }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: Rscript R/secrets.R
